platform :ios, '9.0'
use_frameworks!

target 'SimpleSwitch_Example' do
  pod 'SimpleSwitch', :path => '../'

  target 'SimpleSwitch_Tests' do
    inherit! :search_paths

    pod 'iOSSnapshotTestCase'
  end
end
